spring.application.name=leaderboard-api

# available strategies: fixed-window-non-atomic, sliding-window-log-non-atomic, fixed-window, sliding-window-log
rate-limiter.strategy=sliding-window-log-non-atomic
rate-limiter.window-duration-seconds=10
rate-limiter.max-requests-per-window=10
