spring.application.name=leaderboard-api

##### Redis connection #####

#redis.hostname=
#redis.port=
#redis.password=

##### rate limiting strategy #####

# available strategies: fixed-window-non-atomic, sliding-window-log-non-atomic, fixed-window, sliding-window-log
rate-limiter.strategy=fixed-window
rate-limiter.window-duration-seconds=10
rate-limiter.max-requests-per-window=10
